---
# use travis container based infrastructure
sudo: false

language: python
python: "2.7"

cache: pip

env:
  - INVENTORY=inventory
  - INVENTORY=inventory_git
  - INVENTORY=inventory_github
  - INVENTORY=inventory_marketplace

# Install ansible
addons:
  apt:
    packages:
    - python-pip
    - php5-cli

install:
  # Install ansible
  - pip install ansible==2.1.1.0

  # Check ansible version
  - ansible --version

  # install dependent role
  - ansible-galaxy install --roles-path=tests/roles --role-file=tests/roles/requirements.yml

script:
  - cd tests

  # Basic role syntax check
  - ansible-playbook test.yml -i ${INVENTORY} --syntax-check

  # run playbook
  - ansible-playbook test.yml -i ${INVENTORY} --connection=local

  # run again to check if it is indempotent
  - ansible-playbook -i ${INVENTORY} test.yml --connection=local > indempotent.log
  - >
    cat indempotent.log
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && cat indempotent.log && exit 1)

#notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
