---
# Use the new container infrastructure
sudo: false

language: python
python: "2.7"

cache: pip

env:
  - INVENTORY=inventory

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible==2.0.2.0

  # Check ansible version
  - ansible --version

  # install dependent role
  - ansible-galaxy install --roles-path=tests/roles --role-file=tests/roles/requirements.yml

script:
  - cd tests

  # Basic role syntax check
  - ansible-playbook test.yml -i ${INVENTORY} --syntax-check

#notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
