---
- name: set ldap_server_name and ldap_server from loop variable
  set_fact:
    ldap_server_name: "{{ item.key }}"
    ldap_server:      "{{ item.value }}"

- name: "add server to config"
  ini_file:
    dest: "{{ piwik_config_file }}"
    section: "{{ piwik_login_ldap.plugin.name }}_{{ ldap_server_name }}"
    option: "{{ ldap_server_item.key }}"
    value: "{{ ( ldap_server_item.value.isdigit() ) | ternary( ldap_server_item.value, '\"' ~ ldap_server_item.value ~ '\"' ) }}"
  with_dict: "{{ ldap_server }}"
  loop_control:
    loop_var: ldap_server_item

- name: "update ldap servers in config"
  ini_file:
    dest:  "{{ piwik_config_file }}"
    section: "{{ piwik_login_ldap.plugin.name }}"
    option: "servers[]"
    value: "\"{{ ldap_server_name }}\""
