---
- name: "install LoginLdap into piwik plugins"

- name: "activate plugin"
  command: "./console plugin:activate {{ piwik_login_ldap.plugin.name }}"
  args:
    chdir: "{{ piwik_install_location }}"

- name: "set piwik config location"
  set_fact:
    piwik_config_file: "{{ piwik_install_location }}/{{ piwik_login_ldap.config.file_name }}"

- name: "add each ldap server to config.ini.php"
  include: "add_server.yml"
  vars:
    ldap_server_name: "{{ item.key }}"
    ldap_server: "{{ item.value }}"
  with_dict: "{{ piwik_login_ldap_servers }}"
