---
- name: "set piwik install path"
  set_fact:
    piwik_path: "{{ piwik_path | default( piwik_install_location ~ '/piwik' ) }}"
    piwik_plugins_path: "{{ piwik_path | default( piwik_install_location ~ '/piwik/plugins' ) }}"

- name: "set piwik config location"
  set_fact:
    piwik_config_file: "{{ piwik_path }}/{{ piwik_login_ldap.config.filename }}"

- name: "install LoginLdap into piwik plugins"
  include: "install_{{ piwik_login_ldap_install_from }}.yml"

- name: "activate plugin"
  command: "./console plugin:activate {{ piwik_login_ldap.plugin.name }}"
  args:
    chdir: "{{ piwik_path }}"
  changed_when: False

- name: "check if plugin is activated"
  shell: "grep -F 'Plugins[] = \"LoginLdap\"' {{ piwik_config_file }}"
  changed_when: False

- name: "add each ldap server to config.ini.php"
  include: "add_server.yml"
  with_dict: "{{ piwik_login_ldap_servers }}"

- name: "add general settings to config.ini.php"
  ini_file:
    dest:  "{{ piwik_config_file }}"
    section: "{{ piwik_login_ldap.plugin.name }}"
    option: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict: "{{ piwik_login_ldap_config }}"

- name: "call console commands"
  command: "./console {{ item }}"
    chdir: "{{ piwik_path }}"
  with_items: "{{ piwik_login_ldap_commands }}"
