---
- name: "set piwik install path"
  set_fact:
    piwik_path: "{{ piwik_path | default( piwik_install_location ~ '/piwik' }}"
    piwik_plugins_path: "{{ piwik_path | default( piwik_install_location ~ '/piwik/plugins' }}"

- name: "set piwik config location"
  set_fact:
    piwik_config_file: "{{ piwik_path }}/{{ piwik_login_ldap.config.file_name }}"

- name: "install LoginLdap into piwik plugins"
  include: "install_{{ piwik_login_ldap_install_from }}.yml"

- name: "activate plugin"
  command: "./console plugin:activate {{ piwik_login_ldap.plugin.name }}"
  args:
    chdir: "{{ piwik_install_location }}"

- name: "add each ldap server to config.ini.php"
  include: "add_server.yml"
  vars:
    ldap_server_name: "{{ item.key }}"
    ldap_server: "{{ item.value }}"
  with_dict: "{{ piwik_login_ldap_servers }}"
